# Generated by Django 4.0.5 on 2022-06-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('websites', models.URLField(max_length=100)),
                ('fundation', models.PositiveIntegerField()),
            ],
        ),
    ]
