# Generated by Django 4.0.5 on 2022-06-05 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='fundation',
            new_name='foundation',
        ),
    ]
